### ISSUE TITLE
[Transcription System] X-SAMPA

### ISSUE THREAD

**Issue by Anaphory** [cldf/clts#108]
I was surprised not to see an X-SAMPA transcription system among the already defined ones. Are you working on it, or is that something that won't happen for one reason or another?

**Comment by LinguList** [comment]
X-Sampa is the same as IPA, @tresoldi was looking into it, but lingpy's x-sampa is converting to IPA, so there's no direct need, etc., or otherwise, you'll need to spell out a lot of thingies. I don't exactly remember where we ended in thatt discussion...

**Comment by tresoldi** [comment]
We pretty much settled that x-sampa is a different expression of IPA, but directly linked to it (if IPA changes, X-sampa is supposed to change too). So, yes, the same as IPA, and it was not necessary to add it (given the many tools already available), not desirable (it would inflate the number of systems without any real advantage besides saying "look how big it is").Em 5 de abr de 2018 6:05 PM, Johann-Mattis List <notifications@github.com> escreveu:X-Sampa is the same as IPA, @tresoldi was looking into it, but lingpy's x-sampa is converting to IPA, so there's no direct need, etc., or otherwise, you'll need to spell out a lot of thingies. I don't exactly remember where we ended in thatt discussion...

**Comment by LinguList** [comment]
I'll close this now, as it seems to have been resolved. We could add an extra mapper for convenience when working with characters, but it is probably as simple to write some kind of a wrapper that does the same...
