### ISSUE TITLE
Before final release: delete roundedness from diacritics

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#124]
Following my [remark](https://github.com/cldf/clts/pull/123#issuecomment-442192791), we need to delete the two lines [here](https://github.com/cldf/clts/blob/master/src/pyclts/transcriptionsystems/bipa/diacritics.tsv#L83), namely those where "roundedness" is a feature. Since the symbols are the same, they are not treated anyway, and we usually do not allow that a base feature of a sound class (vowel's base features are roundedness, height, centrality) is modified, unless we put the diacritic explicitly in the vowels.tsv.

**Comment by tresoldi** [comment]
The problem here is that people use these diacritics in a confusing way, sometimes to go from unrounded to rounded when there is no base glyph for the second one (like for `æ`), sometimes to indicate labialization of consonants, sometimes to distinguish among plain, compressed, and protruded...

But I agree with you, using the diacritics only for what is now feature `rounding` makes sense. I can take of this, and while I am at it I can add that normalization we know it is missing. What are Robert's plan on releasing?

**Comment by LinguList** [comment]
I mean: for our case, there's no problem, just a rule: the line is AMBIGUOUS now, can't be parsed, so delete it, and stick to the rule that says: diacritics can't override base features, instead put base sound + diacritic into the vowel.tsv or consonant.tsv. Full stop. Nothing to change. Keep less rounded etc. for the original usage: it means "less rounded" in ipa charts, nothing more.

**Comment by tresoldi** [comment]
Ok, that's easy. But as a side-note, as I pointed in the PR, the rule of diacritics not overriding base features clashes with IPA usage of linguo-labials (this is a stupid problem of the IPA, but unfortunately is what we have).

**Comment by LinguList** [comment]
Examples, please, I don't know what that is, sorry.

**Comment by tresoldi** [comment]
You can see at the bottom of the official table (it is confusing as hell, because it is not a normal row/column table, there are some heavier edges) that the IPA accepts linguo-labialitiy as a **primary** articulation, but the only to express it is with the seagull diacritic: https://upload.wikimedia.org/wikipedia/commons/9/94/Extended_IPA_chart_2005.png

This is more clear in the Wikipedia page on the IPA: https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Pulmonic_consonants

Now, linguolabiality is indeed an unusual feature, but the point is that the IPA accepts its existence without allowing to express it with primary graphemes. This is probably due to the dispute of phoneticists on whether it is a modified coronal or a modified bilabial (as in theory you can express it with the apical diacritic too).

**Comment by LinguList** [comment]
This is no problem, as I mentioned: if you have things that can only be expressed by a sound + diacritic, you HAVE to place them in vowels.tsv or consonantst.tsv, no deal, but you can't take the shortcut via diacritics.tsv. That's all I meant. So there should not be a diacritic in diacritics.tsv that says "linguo-labial".

**Comment by tresoldi** [comment]
Ok, but this means that we need to all the potential linguo-labials by hand. My issue was that I was adding the "accepted" ones, but I didn't want people complaining "oh, you don't allow me to express this speech disorder that is, who know, a linguolabial lateral affricate".

I'll add those which are are listed in WIkipedia, which is good enough for the time being and, of course, gives more coverage of the `wikipedia` set.

**Comment by LinguList** [comment]
I don't really care how much we add, etc., but it is what I did when making the first real bulk of clts, and this is the only way to do it, and it has shown to work. In principle, using the JS tool I worte, it is not that problematic to generate all potential ones. I did that for tones, and I did that for many other features.

**Comment by tresoldi** [comment]
It is already there in the PR I just made :wink:

The linguolabials make sense because, apparently, they are a distinctive feature of a cluster of Vanuatu languages (we should actually ask the specialists at the department what is their take on that)
