### ISSUE TITLE
Add tests for current code

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#35]
It is time to add some tests, especially on known and unknown sounds, as we need to make sure how the things behave. We also need to have a fixed list of all features that are allowed (currently, this is not yet tested).

**Comment by LinguList** [comment]
first test: we need to make sure that new features are only added when really needed, so this is our current list of features:

```
{
  "release": [
    "unreleased",
    "with-dental-fricative-release",
    "with-lateral-release",
    "with-mid-central-vowel-release",
    "with-nasal-release",
    "with-voiceless-velar-fricative"
  ],
  "palatalization": [
    "labio-palatalized",
    "palatalized"
  ],
  "end": [
    "high",
    "low",
    "mid-high",
    "mid-low"
  ],
  "labialization": [
    "labialized"
  ],
  "feature": [
    "annotation",
    "boundary",
    "nasality"
  ],
  "secondary": [
    "uvular-affricate",
    "uvular-aspirated-plosive",
    "uvular-ejective-affricate",
    "uvular-ejective-plosive",
    "uvular-fricative",
    "uvular-plosive",
    "uvular-voiced-aspirated-plosive",
    "uvular-voiced-ejective-plosive",
    "uvular-voiced-plosive",
    "voiced-glottal"
  ],
  "glottalization": [
    "glottalized"
  ],
  "syllabicity": [
    "non-syllabic",
    "syllabic"
  ],
  "stress": [
    "primary-stress",
    "secondary-stress"
  ],
  "rhotacization": [
    "rhotacized"
  ],
  "centrality": [
    "back",
    "central",
    "front",
    "near-back",
    "near-front"
  ],
  "place": [
    "alveolar",
    "alveolo-palatal",
    "bilabial",
    "dental",
    "epiglottal",
    "glottal",
    "labial",
    "labialized-palatal",
    "labialized-velar",
    "labio-dental",
    "labiodental",
    "labiovelar",
    "lateral",
    "palatal",
    "palatal-velar",
    "pharyngeal",
    "postalveolar",
    "retroflex",
    "uvular",
    "velar"
  ],
  "height": [
    "close",
    "close-mid",
    "mid",
    "near-close",
    "near-open",
    "nearly-open",
    "open",
    "open-mid"
  ],
  "preceding": [
    "postoralized",
    "pre-aspirated",
    "pre-glottalized",
    "pre-nasalized",
    "preglottalized"
  ],
  "ejection": [
    "ejective"
  ],
  "phonation": [
    "breathy-voiced",
    "creaky-voiced",
    "extra-voiced",
    "ultra-short",
    "unvoiced",
    "voiced",
    "voiceless"
  ],
  "aspiration": [
    "aspirated"
  ],
  "voicing": [
    "devoiced",
    "revoiced"
  ],
  "value": [
    "morpheme",
    "sandhi",
    "user"
  ],
  "tone": [
    "with_downstep",
    "with_extra-high_tone",
    "with_extra_low_tone",
    "with_falling_tone",
    "with_global_rise",
    "with_global_fall",
    "with_high_tone",
    "with_low_tone",
    "with_mid_tone",
    "with_rising_tone",
    "with_upstep"
  ],
  "manner": [
    "affricate",
    "approximant",
    "flap",
    "fricative",
    "implosive",
    "lateral-affricate",
    "lateral-approximant",
    "lateral-flap",
    "lateral-fricative",
    "nasal",
    "plosive",
    "sibilant-affricate",
    "sibilant-fricative",
    "stop-cluster",
    "stop-segment",
    "tap",
    "trill"
  ],
  "pharyngealization": [
    "pharyngealized"
  ],
  "contour": [
    "contour",
    "falling",
    "flat",
    "rising",
    "short"
  ],
  "velarization": [
    "velarized"
  ],
  "duration": [
    "long",
    "mid-long",
    "ultra-long"
  ],
  "nasalization": [
    "nasalized"
  ],
  "frication": [
    "with-frication"
  ],
  "roundedness": [
    "rounded",
    "unrounded"
  ]
}
```

It would be useful, if @cormacanderson and maybe also @thiagochacon could have a look. @lingulist should also add, where these features effectively occur.

**Comment by LinguList** [comment]
By the latter, I mean, in which sound type (consonant, vowel, etc.)

**Comment by xrotwang** [comment]
Ok. So that's a start towards tests for data consistency. I'd be interested in test data for the pyclts code. I guess some translations could be a good start, like
```python
{
    ('bipa', 'abcd'): ('asjp', 'efgh'),
    ...
}
```

**Comment by LinguList** [comment]
Okay, here's a more important update for the data:

```
{
  "contour": {
    "tone": [
      "falling",
      "flat",
      "contour",
      "rising",
      "short"
    ]
  },
  "secondary": {
    "click": [
      "uvular-voiced-aspirated-plosive",
      "uvular-ejective-plosive",
      "uvular-aspirated-plosive",
      "uvular-affricate",
      "voiced-glottal",
      "uvular-ejective-affricate",
      "uvular-fricative",
      "uvular-voiced-plosive",
      "uvular-plosive",
      "uvular-voiced-ejective-plosive"
    ]
  },
  "value": {
    "marker": [
      "sandhi",
      "user",
      "morpheme"
    ]
  },
  "feature": {
    "marker": [
      "boundary",
      "nasality",
      "annotation"
    ]
  },
  "release": {
    "consonant": [
      "with-mid-central-vowel-release",
      "with-lateral-release",
      "with-nasal-release",
      "with-voiceless-velar-fricative",
      "with-dental-fricative-release",
      "unreleased"
    ]
  },
  "duration": {
    "consonant": [
      "long"
    ],
    "vowel": [
      "mid-long",
      "ultra-short",
      "ultra-long"
    ]
  },
  "pharyngealization": {
    "consonant": [
      "pharyngealized"
    ]
  },
  "ejection": {
    "consonant": [
      "ejective"
    ]
  },
  "rhotacization": {
    "vowel": [
      "rhotacized"
    ]
  },
  "aspiration": {
    "consonant": [
      "aspirated"
    ]
  },
  "end": {
    "tone": [
      "mid-high",
      "high",
      "mid-low"
    ]
  },
  "height": {
    "vowel": [
      "mid",
      "close-mid",
      "near-open",
      "open-mid",
      "open",
      "near-close",
      "close",
      "nearly-open"
    ]
  },
  "tone": {
    "vowel": [
      "with_low_tone",
      "with_falling_tone",
      "with_glogal_fall",
      "with_high_tone",
      "with_global_rise",
      "with_downstep",
      "with_extra-high_tone",
      "with_extra_low_tone",
      "with_upstep",
      "with_rising_tone",
      "with_mid_tone"
    ]
  },
  "velarization": {
    "consonant": [
      "velarized"
    ]
  },
  "nasalization": {
    "consonant": [
      "nasalized"
    ]
  },
  "palatalization": {
    "consonant": [
      "labio-palatalized",
      "palatalized"
    ]
  },
  "preceding": {
    "consonant": [
      "pre-nasalized",
      "pre-glottalized",
      "pre-aspirated"
    ],
    "clicks": [
      "pre-glottalized",
      "postoralized"
    ]
  },
  "frication": {
    "vowel": [
      "with-frication"
    ]
  },
  "voicing": {
    "consonant": [
      "devoiced",
      "revoiced"
    ]  
  },
  "stress": {
    "consonant": [
      "secondary-stress",
      "primary-stress"
    ],
    "vowel": [
      "secondary-stress",
      "primary-stress"
    ]
  },
  "roundedness": {
    "vowel": [
      "unrounded",
      "rounded"
    ]
  },
  "labialization": {
    "consonant": [
      "labialized"
    ]
  },
  "place": {
    "consonant": [
      "pharyngeal",
      "labialized-velar",
      "labial",
      "bilabial",
      "dental",
      "epiglottal",
      "alveolar",
      "labio-dental",
      "lateral",
      "retroflex",
      "palatal-velar",
      "labialized-palatal",
      "glottal",
      "velar",
      "labiovelar",
      "uvular",
      "postalveolar",
      "palatal",
      "alveolo-palatal"
    ]
  },
  "centrality": {
    "vowel": [
      "near-front",
      "front",
      "near-back",
      "central",
      "back"
    ]
  },
  "syllabicity": {
    "consonant": [
      "syllabic"
    ],
    "vowel": [
      "non-syllabic"
    ]
  },
  "start": {
    "tone": [
      "low",
      "mid-low",
      "high",
      "mid-high",
      "mid"
    ]
  },
  "manner": {
    "consonant": [
      "flap",
      "approximant",
      "lateral-approximant",
      "stop-segment",
      "plosive",
      "nasal",
      "stop-cluster",
      "lateral-flap",
      "affricate",
      "sibilant-fricative",
      "fricative",
      "trill",
      "implosive",
      "lateral-affricate",
      "sibilant-affricate",
      "lateral-fricative",
      "tap"
    ]
  },
  "glottalization": {
    "consonant": [
      "glottalized"
    ]
  },
  "phonation": {
    "consonant": [
      "breathy-voiced",
      "creaky-voiced",
      "voiced"
    ],
    "click": [
      "voiced",
      "voiceless"
    ]
  }
}
```

It means, one feature change, will send you this data now via email.

**Comment by cormacanderson** [comment]
The following, I would consider unnecessary and would like to see data that warrant them:
1)
"release": {
    "consonant": [
      "with-mid-central-vowel-release",
      "with-voiceless-velar-fricative",
      "with-dental-fricative-release",
    ]
The second two are likely to be affricated stops, i.e. [tᶿ] and [kˣ]. We could reword this as "with-fricative-release" or "with-affricate-release", or even put them under "aspriation" instead (we could also think of adding aspiration here, i.e. "with-aspiration". After all it is a release feature, and we could lose that feature altogether there. The "with-mid-central-vowel-release" could be renamed "with-schwa-release" or "with-vocalic-release". It's not entirely clear to me if that is even necessary, but we can see.
2)
"palatalization": {
    "consonant": [
      "labio-palatalized",
      "palatalized"
    ]
We might ask why we can't just deal with this as "palatalization:palatalized" and "labialization:labialized" together. I presume each segment cannot be specified more than once for the same feature, otherwise we could just do "sec_localization" (or "sec_place", but I disprefer this  terminology, also "place"), and have "palatalized", "labialized", etc.
3)
},
  "place": {
    "consonant": [
      "labialized-velar",
      "lateral",
      "palatal-velar",
      "labialized-palatal",
      "labiovelar",
    ]
I disprefer "place" over "localization", but anyway. I presume "labialized-velar" should be just "velar" and "labialization:labialized". As for "labialized-palatal" I don't see any reason for not just having that as "palatal" plus "labialization:labialized:. There is probably a case for retaining "labiovelar", given the cross-linguistic frequency of [w], [kp] etc. (note, "labiovelar" ≠ "labialized-velar"). The feature "palatal-velar" is questionable – is it "velar" plus "palatalization:palatalized" as in Irish or Russian, or what? I don't think "lateral" belongs here at all. It's not a place feature and was actually causing trouble with the consonants (see below).
4) 
"height": {
    "vowel": [
      "mid",
      "close-mid",
      "near-open",
      "open-mid",
      "open",
      "near-close",
      "close",
      "nearly-open"
For a start, "near-open" and "nearly-open" look like aliases. I would prefer using high-low here, personally: "high, near-high, mid-high, mid, mid-low, near-low, low".
5)
"manner": {
    "consonant": [
      "flap",
      "lateral-approximant",
      "stop-segment",
      "plosive",
      "nasal",
      "stop-cluster",
      "lateral-flap",
      "sibilant-fricative",
      "lateral-affricate",
      "sibilant-affricate",
      "lateral-fricative",
      "tap"
    ]
This is a bit of a mess, and I don't think we are dealing with it in the best way. Numerous points: a) "tap" and "flap" are likely aliases – how do we distinguish? b) for "plosive" and "nasal" it might be more principled to call them "oral-stop" and "nasal-stop", c) can you clarify what "stop-segment" and "stop-cluster" actually mean – these look like structural features which should be taken out of here – they aren't manner, d) I would propose two new features: "laterality:lateral" and "sibilancy:sibilant" – that will mean we can make all of the above unary and make the description much more straightforward, e.g. currently we have [tθ] as "dental-affricate" and [ts] as "dental-sibilant-affricate", while this change would have the former as "dental-affricate" and the latter as "dental-affricate-sibilancy:sibilant".
6)
  },
  "frication": {
    "vowel": [
      "with-frication"
Is it really necessary? Fang Lu and Feng Ling ("Fricative vowels as an intermediate state of vowel apicalization") say: "plain high vowels, fricative high vowels, and apical vowels distinguish in place of    articulation, namely being anterodorsal, laminal, and apical respectively; and frication becomes a concomitant and redundant feature in the production of fricative or apical vowels".
