### ISSUE TITLE
how to handle laminals?

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#64]
Do we define them in terms of manner, or rather in terms of "laminality"? As with laterality, there are two possibilities:

1 voiceless lamino-dental stop consonant [t̻]]
2 voiceless laminal dental stop consonant [t̻]]

**Comment by thiagochacon** [comment]
In principle whatever treatment given to laminals should be the same as other tongue regions (apical, dorsal, etc.). All are active articulators.

Most of these coallesce with terminologies that refers only to the fixed/passive articulators, such as dental, alveolar alveopalatal.

Perhaps lamino-dental is the same as "interdental".

However we do find descriptions where laminal and apical tongue positions are explicitly distinguished in the articulation of front obstruents. For instance lamino-dental vs. Apico-dental. Or lamino-retroflex vs. Apico-retroflex.

In order to be fully consistent, my inclination is to keep descriptions of active and passive articulators altogether, such as labiodental, apico-alveolar, etc., Whenever contrastove values are possible.

Em 21 de dez de 2017 10:06, Johann-Mattis List <notifications@github.com> escreveu:

Do we define them in terms of manner, or rather in terms of "laminality"? As with laterality, there are two possibilities:

1 voiceless lamino-dental stop consonant [t̻]]
2 voiceless laminal dental stop consonant [t̻]]

**Comment by LinguList** [comment]
I went with "laminality" now (see #66), because it is expressed by a diacritic, which means, we can generate sounds which have base "X" + "laminal diacritic". This makes the system more productive. 

Ah, forgot to say: this system is not yet updated, need to make a PR later, but I'm waiting until things accumulate. FYI: we now generate 1500 sounds of Phoible consistently (i.e., they are properly parsed), which is an argument for decomposition and analyticity.
