### ISSUE TITLE
Adding a feature "whistled" or is this an overkill?

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#71]
Lapsyd gives these data:
```
s̫ pulmonic fricative sibilant voiceless alveolar whistled
z̫ pulmonic fricative sibilant voiced alveolar whistled
ʃ̫ pulmonic fricative sibilant voiceless palato-alveolar whistled
ʒ̫ pulmonic fricative sibilant voiced palato-alveolar whistled
ts̫ pulmonic affricate sibilant voiceless alveolar whistled
dz̫ pulmonic affricate sibilant voiced alveolar whistled
t̠ʃ̫ pulmonic affricate sibilant voiceless palato-alveolar retracted whistled
d̠ʒ̫ pulmonic affricate sibilant voiced palato-alveolar retracted whistled
ts̫ʼ ejective affricate sibilant alveolar whistled
t̠ʃ̫ʼ ejective affricate sibilant palato-alveolar retracted whistled
ts̫ʰ pulmonic affricate sibilant aspirated voiceless alveolar whistled
t̠ʃ̫ʰ pulmonic affricate sibilant aspirated voiceless palato-alveolar retracted whistled
```
I don't know what "whistled" means, but I think it is the diacritic mark they have under the sounds. Is it worth adding them?

**Comment by thiagochacon** [comment]
this is a special kind of sibilant coarticulation, where the lips are rounded to enhance the "sibilancy" of the sound.

**Comment by tresoldi** [comment]
The `whistled` feature come from Nakh-Dagestanian languages such as [Tabasaran](http://www.lapsyd.ddl.ish-lyon.cnrs.fr/lapsyd/index.php?data=view&code=10041), where they note:

> A notable feature of Tabasaran is the extensive set of "whistled" sibilants. These are produced with a lip-rounding gesture that creates a separate sound source superimposed on the sibilant spectrum. 

In my system I am treating it as a "superlabialization", using the same features for vowel protrusion (note that the diacritic they emply is precisely the one for protrusion) -- remember that my features are used for all sounds (vowels/consonants) and are floating-points, so you can distinguish between compressed and protruded.

I am not entirely sure about the need to include it as something different from "labialized": it seems a phonetic rather than phonological differentiation, and quickly browsing the inventories I cannot find a language where labialized and whistled are distinctive, suggesting minimal pairs. I'd skip it or map it to `labialized`.

**Comment by thiagochacon** [comment]
seems fair to treat them as labialized for the sake of simplicity, but that is a bit inexact to the extent that s̫ and sʷ are articulatorily not the same thing

**Comment by LinguList** [comment]
We'll just ingore those things for the moment. If scholars want to work on those languages in the future with help of the CLTS system, they can add the feature and make a PR, we have already enough different sounds, even without this.
