### ISSUE TITLE
check when writing whether the number of sumbols is unchanged

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#78]
```
ʰʷsʰ
```

This will be read as:

```python
>>> bipa['ʰʷsʰ'].s
ʷsʰ
```
because we don't allow for pre-aspiration and pre-labialization as the same feature. Admittedly, the sound is strange, but unless we mark it explicitly as alias, we should probably not link to it. So either modify the transcriptiondata.py file to check for identical number of symbols in source and sound.s or add them manually as aliased sequences.

**Comment by tresoldi** [comment]
It is indeed rather strange. I saw that it comes from the Soghpo Tibetan in Eurasian, with source (commented as `"A monster. Independent verification is definitely in order."` by Eurasian's authors)

> Suzuki, Hiroyuki. 2011. Dialectal particularities of Sogpho Tibetan – an introduction to the “Twenty-four villages’ patois.” In Turin, Mark; and Bettina Zeisler. 2011. Himalayan Languages and Linguistics: Studies in Phonology, Semantics, Morphology and Syntax, 55–73.

I could read most of the paper on Google Books. It is **not** listed in the consonantal inventory, but pre-aspiration is presented in a list of initial consonant clusters and the authors might have composed it on their own based on the description. The closer example I could find is **`ʰsʰẽ mo** ("elder sister", the first charater is a tone mark).

My guess is that this "pre-aspiration" is actually a glottal frication, so that we have a /hsʰ/ cluster working as a phoneme -- the part of the paper I cannot read (p. 64 on) seems to be exactly about the complex initial clusters of the Sogpho dialects they are describing. I suggest to leave it unlinked for the time being and to keep the issue open (perhaps removing it from the milestone), but I defer to the Sino-Tibetan experts.

**Comment by LinguList** [comment]
well, if it's Tibetan, no wonder, as people often have very minute claims on the phonetics and phonology there, but in the end, it is barely audible when the speakers speak in daily life, only when they pronounce it when reading. So it may also be artificial, as the speakers will try to pronounce the prefixes in their alphabet in elicitation situations, etc. 

We can take this as an example in the paper where we actually refuse to adjust our system for the moment (with the last update we have already some 3800 different symbols, and we show how low the overlap between the systems is). So this will be closed once I adjusted the control procedure.
