### ISSUE TITLE
Uralic Phonetic Alphabet 

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#79]
This could be easily added, at least in a rudimentary version.

**Comment by tresoldi** [comment]
I'm on it.

**Comment by tresoldi** [comment]
I've just merged my branch, but I am not closing this issue due to some things to consider (already listed in the PR, but I'll copy it here):

- some graphemes are missing, mostly turned and rotated glyphs, I need to check the Unicode code data and actual usage to make sure how they are code. As far as I can tell, these missing graphemes are not that common.
- some clean-up is probably due in the vowel listing, now that diacritics have been implemented. Of course, one need to take care in terms of pre-composed glyphs.

Some actual UPA data would be helpful, do you have any at hand?
